name: Deploy MovieAPI Project

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  

      - name: Build Java project
        run: |
          cd movies
          ./mvnw clean package 

      - name: Deploy to Render
      
